<template>
  <div class="container mx-auto mt-[115px] pb-[20px]">
    <div class="mb-10 flex justify-between md:block">
      <div>
        <h1 class="text-3xl font-bold">Announcements</h1>
        <p class="font-medium">
          View, create, or edit announcements for all employees of your company.
        </p>
      </div>
      <button
        class="btn min-h-0 h-[38px] mt-[22px] border-none rounded-md text-white normal-case bg-primary-500 hover:bg-primary-700 sm:w-full"
      >
        <font-awesome-icon class="mr-2" :icon="['fas', 'plus']" />
        <span>Post an Announcement</span>
      </button>
    </div>
    <div class="flex justify-between md:block">
      <div class="block md:mb-5">
        <button
          class="btn btn-ghost min-h-0 h-[38px] mr-2 bg-[#e6ffee] border-none rounded-md normal-case hover:bg-slate-200"
        >
          <span class="badge bg-primary-500 border-none text-white px-3 mr-2">
            10
          </span>
          <span>All</span>
        </button>
        <button
          class="btn btn-ghost min-h-0 h-[38px] border-none rounded-md normal-case hover:bg-slate-200"
        >
          <span class="badge bg-orange-500 border-none text-white px-3 mr-2">
            10
          </span>
          <span>Drafts</span>
        </button>
      </div>
      <div class="flex sm:block">
        <select
          class="select mr-4 min-h-0 h-[42px] w-[300px] bg-transparent border-1 border-slate-400 rounded-md focus:outline-none sm:mb-3 sm:w-full"
        >
          <option disabled selected>Filter By</option>
        </select>
        <div class="flex">
          <input
            class="input min-h-0 h-[42px] w-[300px] bg-transparent border-1 border-r-0 border-slate-400 rounded-tl-md rounded-bl-md rounded-r-none focus:outline-none sm:w-full"
            type="text"
            placeholder="Search..."
          />
          <button
            class="btn btn-ghost min-h-0 h-[42px] rounded-rl-md rounded-rl-md rounded-l-none border-1 border-l-0 border-slate-400 hover:bg-slate-200 hover:border-slate-400"
          >
            <font-awesome-icon :icon="['fas', 'magnifying-glass']" />
          </button>
        </div>
      </div>
    </div>

    <EasyDataTable
      class="mt-6"
      :headers="tableData.headers"
      :items="tableData.items"
    >
      <template #loading>
        <img
          src="https://i.pinimg.com/originals/94/fd/2b/94fd2bf50097ade743220761f41693d5.gif"
          style="width: 100px; height: 80px"
        />
      </template>
    </EasyDataTable>
  </div>
</template>

<script setup>
// Base Imports
import { ref } from 'vue';

const tableData = ref({
  headers: [
    { text: 'TITLE', value: 'title', sortable: true },
    { text: 'MESSAGE', value: 'message', sortable: true },
    { text: 'SENT BY', value: 'sent_by', sortable: true },
    { text: 'SENT THROUGH', value: 'sent_through', sortable: true },
    { text: 'DATE CREATED', value: 'date_created', sortable: true },
    { text: 'START DATE', value: 'start_date', sortable: true },
    { text: 'END DATE', value: 'end_date', sortable: true, width: 200 },
  ],
  items: [
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
    {
      title: 'asdasdasdasdas ',
      message: 'GSWasdasdasdasd',
      sent_by: 'Ron, Ken',
      sent_through: '<> <>',
      date_created: '02/17/2022',
      start_date: '02/18/2022',
      end_date: '02/22/2022',
    },
  ],
});
</script>
